#!/usr/bin/env bash
#
# Remove crash data generated by kexec-tools
set -o errexit

crash_data_location=(
    "/var/crash/*"
    "/var/log/dump/*"
)

# Include hidden files in glob
shopt -s nullglob dotglob

for crash_data in ${crash_data_location[@]}
do
    rm -rf ${crash_data}
done

exit 0
