#!/usr/bin/env bash
#
# Remove crash data generated by kexec-tools

CRASH_DATA_LOCATIONS=(
    "/var/crash/*"
    "/var/log/dump/*"
)

# Include hidden files in glob
shopt -s nullglob dotglob

for CRASH_DATA in ${CRASH_DATA_LOCATIONS[@]}
do
    rm -rf ${CRASH_DATA}
done

exit 0
