#!/usr/bin/env bash
#
# Remove crash data generated by kexec-tools
set -o errexit

crash_data_location=(
    "/var/crash/*"
    "/var/log/dump/*"
)

# crash_data: Remove crash data generated by kexec-tools by removing:
#     * /var/crash/*
#     * /var/log/dump/*
echo "*** Removing any crash data or dumps created by kexec-tools"

# Include hidden files in glob
shopt -s nullglob dotglob

# shellcheck disable=SC2068
for crash_data in ${crash_data_location[@]}
do
    rm -rf "${crash_data}"
done

exit 0
